dinar: update and change to netboot
ponkila/homestaking-infra pull request #67
Opened 2024-01-11 09:07 UTC by tupakkatapa

2024-01-21 17:02 UTC, jhvst requested changes

2024-01-21 17:02 UTC, jhvst commented on nixosConfigurations/dinar-ephemeral-alpha/secrets/default.yaml
removing secrets needs to be reflected in .sops.yaml

2024-01-21 17:06 UTC, tupakkatapa commented on flake.nix
> +            }
Should this change be made straight to the kexecTree module?

2024-01-21 17:06 UTC, jhvst commented on flake.nix
> +            }
works for me

2024-01-21 17:08 UTC, tupakkatapa commented on flake.nix
> +            }
Forgot that it is in a different repo, making the changes here at least for now.

2024-01-21 19:27 UTC, jhvst commented on flake.nix
> -              };
I think these might not be possible to be removed -- the RPi boots from the GPU and might thus require its own bootloader to be present.

2024-01-21 19:27 UTC, jhvst commented
otherwise lgtm

2024-01-21 20:20 UTC, merged

2024-01-22 15:08 UTC, jhvst commented
Realized yesterday that the README has to be updated, currently the dinar hosts are labeled as ISO images.

2024-01-22 18:03 UTC, tupakkatapa commented
Pushed the missing README update straight to main: https://github.com/ponkila/homestaking-infra/commit/9d9b7e00a24b2e96702e1c43760e699389682bf8